### PR TITLE
[build] fix build-[ot]tf.sh for Xidel 0.9.8

### LINKED ISSUE #2: I can't get the parallel processing scripts to work
@ctrlcctrlv with so many styles I agree parallel processing is super useful, but I can't seem to run the new scripts.

`GENERATING TTF`
.
`**** Processing: data:,<empty/> ****`
`build-ttf.sh: line 41: parallel: command not found`

`./build-otf.sh: line 66: unexpected EOF while looking for matching `"'`

these are the errors I get when I try and run the new build scripts. I am (as always) not very good with the computers, so it is more than likely that I'm doing something wrong here.

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Closes #2.

### CODE REVIEW

File: sources/build-ttf.sh [hunk 1]
```diff
@@ -37,7 +37,7 @@ genttf() {
 	rm -rf $TT_DIR
 	mkdir -p $TT_DIR
 
-	instances="$(xidel -e 'root()//instances//instance/@name' < designspace/MFEK-Sans.designspace)"
```
Comment (ctrlcctrlv) [inline sources/build-ttf.sh:40]: stdin read only allowed it seems on Xidel 0.9.9
